# Generated by Django 4.1.1 on 2022-11-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auctions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_id', models.IntegerField(default=1)),
                ('item', models.CharField(max_length=50)),
                ('image', models.URLField()),
                ('starting_bid', models.IntegerField()),
                ('starting_time', models.DateTimeField(auto_now_add=True)),
                ('ending_time', models.DateTimeField()),
                ('highest_bid', models.FloatField(default=0, null=True)),
                ('winner_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
